-- AGHU
INSERT INTO agh.aip_pacientes (codigo, prontuario, nome) VALUES (1, 123, 'FULANO DE TAL');
INSERT INTO agh.ain_leitos (lto_id) VALUES ('0110A');
INSERT INTO agh.ain_leitos (lto_id) VALUES ('0110B');
INSERT INTO agh.ain_leitos (lto_id) VALUES ('0120A'); 
INSERT INTO agh.ain_leitos (lto_id) VALUES ('0120B');
INSERT INTO agh.ain_internacoes(seq, dthr_internacao, ind_paciente_internado, pac_codigo, lto_lto_id) VALUES (1, '2023-02-01 08:00:00', 'S', 1, '0110A');
INSERT INTO agh.agh_atendimentos(seq, origem, pac_codigo) VALUES (1, 'Teste', 1);
INSERT INTO agh.agh_atendimentos(seq, origem, pac_codigo) VALUES (2, 'Teste2', 1);

INSERT INTO agh.mpm_prescricao_dietas(seq, atd_seq, observacao) VALUES (1, 2, 'Deu Certo');

INSERT INTO cirurgia.locais_origem (id, descricao) VALUES (1, 'SAA'); 
INSERT INTO cirurgia.locais_origem (id, descricao) VALUES (2, 'UTI'); 
INSERT INTO cirurgia.locais_origem (id, descricao) VALUES (3, 'PRONTO SOCORRO'); 
INSERT INTO cirurgia.locais_origem (id, descricao) VALUES (4, 'ENFERMARIA'); 
INSERT INTO cirurgia.locais_origem (id, descricao) VALUES (5, 'LEITO'); 

INSERT INTO cirurgia.tipos_precaucao (id, descricao) VALUES (1, 'PADRÃO');
INSERT INTO cirurgia.tipos_precaucao (id, descricao) VALUES (2, 'CONTATO');
INSERT INTO cirurgia.tipos_precaucao (id, descricao) VALUES (3, 'AEROSSOL');
INSERT INTO cirurgia.tipos_precaucao (id, descricao) VALUES (4, 'RESPIRATÓRIO');
INSERT INTO cirurgia.tipos_precaucao (id, descricao) VALUES (5, 'REVERSO');

INSERT INTO cirurgia.especialidades_cirurgicas (id, descricao) VALUES (1, 'CIRURGIA BUCOMAXILOFACIAL');
INSERT INTO cirurgia.especialidades_cirurgicas (id, descricao) VALUES (2, 'CIRURGIA CARDIOVASCULAR'); 
INSERT INTO cirurgia.especialidades_cirurgicas (id, descricao) VALUES (3, 'CIRURGIA DE CABEÇA E PESCOÇO'); 

INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '>=  41', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '39 a 40,9', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '38,5 a 38,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '36 a 38,4', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '34 a 35,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '32 a 33,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '30 a 31,9', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (1, '<= 29,9', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '> 160', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '130 a 159', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '110 a 129', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '70 a 109', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '50 a 69', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (2, '<= 49', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '>= 180', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '140 a 179', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '110 a 139', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '70 a 109', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '55 a 69', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '40 a 54', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (3, '<= 39', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '>= 50', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '35 a 49', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '25 a 34', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '12 a 24', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '10 a 11', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '6 a 9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (4, '<= 5', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, '>= 500', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, '350 a 499', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, '200 a 349', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, '< 200 ou PaO2 > 70', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, 'PaO2 de 61 a 70', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, 'PaO2 de 55 a 60', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (5, 'PaO2 < 55', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, 'arterial>= 7,7; >= 52', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '7,6 a 7,69 ; 41 a 51,9', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '7,5 a 7,59 ; 32 a 40,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '7,33 a 7,49 ; 22 a 31,9', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '7,25 a 7,32 ; 18 a 21,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '7,15 a 7,24 ; 15 a 17,9', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (6, '< 7,15 ; < 15', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '>= 180', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '160 a 179', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '155 a 159', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '150 a 154', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '130 a 149', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '120 a 129', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '111 a 119', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (7, '< 110', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '>= 7', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '6 a 6,9', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '5,5 a 5,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '3,5 a 5,4', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '3 a 3,4', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '2,5 a 2,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (8, '< 2,5', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '>= 3,5', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '> 3,5 na ARF', 8);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '2 a 3,4', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '2 a 3,4 na ARF', 6);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '1,5 a 1,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '1,5 a 1,9 na ARF', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '0,6 a 1,4', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (9, '< 0,6', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '>= 60', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '50 a 59,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '46 a 49,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '30 a 45,9', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '20 a 29,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (10, '< 20', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '>= 40', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '20 a 39,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '15 a 19,9', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '3 a 14,9', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '1 a 2,9', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (11, '< 1', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '15', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '14', 1);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '13', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '12', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '11', 4);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '10', 5);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '9', 6);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '8', 7);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '7', 8);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '6', 9);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '5', 10);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '4', 11);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (12, '<=3', 12);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (13, '>= 75', 6);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (13, '65 a 74', 5);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (13, '55 a 64', 3);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (13, '45 a 54', 2);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (13, '<= 44', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (14, 'nenhum', 0);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (14, 'não cirúrgico', 5);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (14, 'cirurgia de emergência', 5);
INSERT INTO evolucoes.apache2_opcoes (questao, label, pontuacao) VALUES (14, 'cirurgia eletiva', 2);